### ISSUE TITLE
Need some way to limit activation of this mod

### ISSUE THREAD

**Issue by gniftygnome** [RakambdaOrg/EditSign#14]
I tried this mod out and got absolutely roasted by my users.  You would think I was killing their kids.  It's too easy to destroy sign content.  Signs with actions (f.e. teleporting the user) are automatically destroyed by this mod the first time someone uses them.

The forge-only SignEdit mod by default requires the user to be holding a sign in their hand in order to activate the mod.  That is one way I think would alleviate the problem.  (Totally fine by me if there's a config file and I have to edit it to enable the workaround...)

Another would be to allow rebinding activation of the mod so some key is required.  The alt key might be a good option.

**Comment by Rakambda** [comment]
The fact that you mention SignEdit and can't use it as an alternative is I guess because you're using Fabric ?

* For the first point (having to hold a (configurable?) item) can be done I guess, will have to look into it.
* Though for the second one (key activation) I don't think it will. The way it works is that it hooks itself on the "right click" event ; and no other event. So I don't know which keys are pressed. I'm only checking that the player isn't sneaking (and not that shift is pressed). And I'd prefer to keep it that way as it doesn't require the mod to be on the client side (I think).

**Comment by gniftygnome** [comment]
> you're using Fabric ?

Yes, and although I've experimented with cardboard it is very pre-alpha right now.

> will have to look into it.

That would be great; personally I think that way makes perfect sense, although most of my users wanted a key press instead.  However,

> it doesn't require the mod to be on the client side (I think).

You are correct; that is how I was (briefly) using it.  I do appreciate any mod that is able to be purely server side (and if not, then purely client side).  The mods that have to be both always raise the spectre of what happens if versions get skewed.

**Comment by gniftygnome** [comment]
Thanks!  FYI to anybody looking for instructions you probably want to set it like this:

{
        // Required item to edit signs
        "requiredItemId": "#minecraft:signs"
}
