### ISSUE TITLE
BetterEnd Support

### ISSUE THREAD

**Issue by ghost** [RakambdaOrg/EditSign#17]
Hello! At this time, with version `1.16.5-2.2.0` of Edit Sign, and version `1.16.4-1.4.0` of BetterEnd (Forge), signs added by BetterEnd are not editable. Would love to see this change!

I saw in #11 you referenced changes that may need to be made on the side of the other mod author - should I post anything on their issue tracker?

Please let me know if you require any more information!

**Comment by Rakambda** [comment]
I guess this is to make EndSign editable right?
If so then I guess it'd have kinda the same problem as #11.

https://github.com/Beethoven92/BetterEndForge/blob/9c2ff82731778003e2902363f36d7c2a6603b320/src/main/java/mod/beethoven92/betterendforge/common/tileentity/ESignTileEntity.java#L30

The tile entity for the sign is extending `TileEntity` and not `SignTileEntity` so from EditSign point of view this is just a "regular" tile entity.

I never really looked deep down on compatibility with other mods, but I think that I can't really hook into it if I don't have their class referenced somewhere (and so that'd make a dependency). Maybe I'm wrong on that though.

The easiest is problably to have their tile entity extend the `SignTileEntity`.
Or they can even make it editable themselves if they want .

**Comment by ghost** [comment]
I wonder how hard that would be for @Beethoven92 to implement (i.e. was there anything stopping the use of `SignTileEntity` in the first place?). 🤔

**Comment by Rakambda** [comment]
Technically everything could be overridden and so it doesn't change that much what it extends.

But extending a class and overriding everything is a bit weird. I guess that the biggest problem was that this SignTE got private fields and redeclaring them in your class is ugly.

Honestly having them add the feature of editing the sign wouldn't be hard I think. But as I read seems like the forge mod only replicates the fabric one; so maybe it's there that the feature can be asked for?

**Comment by Beethoven92** [comment]
While its true we don't add features that the original mod doesn't have, we can do exceptions if those features are enhancements of already existing features, which would be the case here. So unfortunately the vanilla sign system is kinda hardcoded to only work with vanilla wood types. I'll see what i can do to work around this. Of course i could implements sign editability in our custom signs myself, but since your mod exists and its purpose is to add that feature, i would prefer to make BetterEnd compatible with it if possible.
