### ISSUE TITLE
Key to disable

### ISSUE THREAD

**Issue by bennetrr** [RakambdaOrg/EditSign#46]
It would be nice to add a key to disable the edit feature completely. When you have signs with onClick commands, the sign editor will open and delete the command. If you stand on the ground, Shift-Click works, but when you sit in a minecart, it doesnt.

**Comment by Rakambda** [comment]
This is similar to #14 .

I'm not really a big fan of adding this "disabling feature" though a key as it'd require the mod to be installed client side (for now it's only required server side).

You can use the the required item to make it so that you need to have a specific item held in order for the GUI to show back up.

**Comment by bennetrr** [comment]
The required item is not perfect, but for now it's good enough.
